### ISSUE TITLE
Can you rewrite to use instance metatdata role to get indexes?

### ISSUE THREAD

**Issue by munntjlx** [divi255/cloud-fancyindex#1]
I use aws s3, and noticed that you use secrets files. If I assign an aws role to retrieve necessary files from s3 bucket (ec2 instanceProfile), I can get things w/o having to hard-code secrets. Here is the relevant boto3 documentation:

IAM Role

If you are running on Amazon EC2 and no credentials have been found by any of the providers above, boto3 will try to load credentials from the instance metadata service. In order to take advantage of this feature, you must have specified an IAM role to use when you launched your EC2 instance. For more information on how to configure IAM roles on EC2 instances, see the IAM Roles for Amazon EC2 guide.

Note that if you've launched an EC2 instance with an IAM role configured, there's no explicit configuration you need to set in boto3 to use these credentials. Boto3 will automatically use IAM role credentials if it does not find credentials in any of the other places listed above.

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html

**Comment by divi255** [comment]
finally have a time/needs to tune this project a little bit, will try also digging your issue as well

**Comment by divi255** [comment]
Please try new bucker JSON indexer (it's moved to separate project, only fancyindex-generator will be left here): https://github.com/divi255/cloudindex

I've allowed there to omit AWS key as well added a couple of new options, e.g. to fetch object custom meta data.

CLI tool params are almost unchanged, new indexer can be also used as embedded library as well.

Output format is the same so it works with current fancyindex-generator w/o any problems.
